services:
  apisvc-documentation-mono:
    container_name: apisvc-doc-mono
    image: pbranestrategy/tac-case-api-service-mono:0.2.9
    environment:
      - SERVER_PORT=8080
      - API_SVC_ENV=secured
      - API_SVC_MAX_FILE_SIZE_MB=20
      - API_SVC_MODE=freshdesk
      - AUTH_SVR_REPO=inMemory
      - AUTH_SVC_ISSUER_URI=http://localhost:8080/oauth2/jwks
      - PG_DATASOURCE_URL=jdbc:postgresql://localhost:5432/tacauthdb
      - PG_DATASOURCE_USERNAME=postgres-user-name
      - PG_DATASOURCE_PASSWORD=postgres-user-password
      - CLIENT_ID=client-id
      - CLIENT_SECRET=client-secret
      - CLIENT_NAME=client-name
      - ACCESS_TOKEN_EXPIRATION_MIN=5
      - FD_API_KEY=0123456789ABCDEFGHI
      - FD_BASE_URI=https://domain.freshdesk.com/api/v2
      - FD_CUSTOMER_NAME=Beacon
      - FD_TAC_CASE_SCHEMA_NAME="TAC Cases"
      - FD_RMA_CASE_SCHEMA_NAME="RMA Cases"
      - FD_DEFAULT_RESPONDER_ID=3043029172572
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    networks:
      - backend
    #    restart: unless-stopped
    profiles:
      - documentation

  apisvc-prod-mono:
    container_name: apisvc-prod-mono
    image: pbranestrategy/tac-case-api-service-mono:0.2.9
    environment:
      - API_SVC_ENV=secured
      - API_SVC_MODE=freshdesk
      - CLIENT_ID=client-id
      - CLIENT_SECRET=client-secret
      - CLIENT_NAME=Beacon
      - FD_API_KEY=0123456789ABCDEFGHI
      - FD_BASE_URI=https://domain.freshdesk.com/api/v2
      - FD_CUSTOMER_NAME=Beacon
      - FD_DEFAULT_RESPONDER_ID=3043029172572
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    networks:
      - backend
    #    restart: unless-stopped
    profiles:
      - production

  apisvc-dev-mono:
    container_name: apisvc-dev-mono
    image: pbranestrategy/tac-case-api-service-mono:0.2.9
    environment:
      - API_SVC_ENV=unsecured
      - API_SVC_MODE=database
      - FD_API_KEY=0123456789ABCDEFGHI
      - FD_BASE_URI=https://domain.freshdesk.com/api/v2
      - FD_CUSTOMER_NAME=Beacon
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    networks:
      - backend
    #    restart: unless-stopped
    profiles:
      - development

  apisvc-test-mono:
    container_name: apisvc-test-mono
    image: pbranestrategy/tac-case-api-service-mono:0.2.9
    environment:
      - API_SVC_ENV=unsecured
      - API_SVC_MODE=freshdesk
      - FD_API_KEY=0123456789ABCDEFGHI
      - FD_BASE_URI=https://domain.freshdesk.com/api/v2
      - FD_CUSTOMER_NAME=Beacon
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    networks:
      - backend
    #    restart: unless-stopped
    profiles:
      - testing

  client-test:
    container_name: client-test-mono
    image: pbranestrategy/tac-case-api-oauth2-sample-client:0.1.7
    environment:
      - TAC_API_HOST=apisvc-test-mono
      - TAC_API_HOST_PORT=8080
      - TAC_AUTH_HOST=apisvc-test-mono
      - TAC_AUTH_HOST_PORT=8080
      - AUTH_BASE_URI=http://apisvc-test-mono:8080
      - RESOURCE_BASE_URI=http://apisvc-test-mono:8080/api/v1
      - TOKEN_EP_URI=/oauth2/token
      - AUTH_EP_URI=/oauth2/authorize
      - USER_INFO_EP_URI=/oauth2/userinfo
      - JWK_SET_EP_URI=/oauth2/jwks
      - CLIENT_ID=client-id
      - CLIENT_SECRET=client-secret
      - CLIENT_NAME=client-name
      - CLIENT_SCOPE=read.cases,write.cases
      - CLIENT_CONN_TIMEOUT=2000
      - CLIENT_RESP_TIMEOUT=3000
    tty: true
    stdin_open: true
    networks:
      - backend
    profiles:
      - testing

  client-dev:
    container_name: client-dev
    image: pbranestrategy/tac-case-api-oauth2-sample-client:0.1.7
    environment:
      - TAC_API_HOST=apisvc-dev-mono
      - TAC_API_HOST_PORT=8080
      - TAC_AUTH_HOST=apisvc-dev-mono
      - TAC_AUTH_HOST_PORT=8080
      - AUTH_BASE_URI=http://apisvc-dev-mono:8080
      - RESOURCE_BASE_URI=http://apisvc-dev-mono:8080/api/v1
      - TOKEN_EP_URI=/oauth2/token
      - AUTH_EP_URI=/oauth2/authorize
      - USER_INFO_EP_URI=/oauth2/userinfo
      - JWK_SET_EP_URI=/oauth2/jwks
      - CLIENT_ID=client-id
      - CLIENT_SECRET=client-secret
      - CLIENT_NAME=client-name
      - CLIENT_SCOPE=read.cases,write.cases
      - CLIENT_CONN_TIMEOUT=2000
      - CLIENT_RESP_TIMEOUT=3000
    tty: true
    stdin_open: true
    networks:
      - backend
    profiles:
      - development

networks:
  backend:
    driver: bridge
